Bugfixes for double spend spams.
iotaledger/iota-core pull request #195
Opened 2023-07-19 12:12 UTC by piotrm50

This PR introduces a bunch of updates found when running double spend spams in local Docker network.

2023-07-19 16:18 UTC, muXxer requested changes

2023-07-20 06:41 UTC, piotrm50 commented on pkg/protocol/engine/tipselection/v1/provider.go
> +					livenessThresholdDuration := time.Duration(uint64(e.LatestAPI().ProtocolParameters().LivenessThreshold())*uint64(e.LatestAPI().ProtocolParameters().TimeProvider().SlotDurationSeconds())) * time.
Is it ok if I just move it 2 lines above, outside of the AcceptedBlockProcessed handler?

2023-07-20 09:09 UTC, alexsporn commented on pkg/protocol/engine/tipselection/v1/provider.go
> +					livenessThresholdDuration := time.Duration(uint64(e.LatestAPI().ProtocolParameters().LivenessThreshold())*uint64(e.LatestAPI().ProtocolParameters().TimeProvider().SlotDurationSeconds())) * time.
`LatestAPI()` is wrong btw, you should use `CurrentAPI()`
Latest could be an already planned protocol upgrade

2023-07-20 09:55 UTC, piotrm50 commented on pkg/protocol/engine/tipselection/v1/provider.go
> +					livenessThresholdDuration := time.Duration(uint64(e.LatestAPI().ProtocolParameters().LivenessThreshold())*uint64(e.LatestAPI().ProtocolParameters().TimeProvider().SlotDurationSeconds())) * time.
> LatestAPI() is wrong btw, you should use CurrentAPI()
Changed that.

2023-07-20 12:52 UTC, muXxer requested changes

2023-07-20 12:52 UTC, muXxer commented on components/debugapi/params.go
> +	Enabled bool `default:"true" usage:"whether the BlockIssuer component is enabled"`
Wrong comment

2023-07-20 12:52 UTC, muXxer commented on components/debugapi/component.go
>  	routeGroup := deps.RestRouteManager.AddRoute("debug/v3")
Oh, we really have v3 of the debug API already? :D

2023-07-21 08:24 UTC, muXxer commented on components/debugapi/component.go
>  	routeGroup := deps.RestRouteManager.AddRoute("debug/v3")
sorry, just had a look in hornet. there we are at v1 so this here should be v2

2023-07-21 09:53 UTC, muXxer approved these changes

2023-07-21 10:46 UTC, merged