Add core API structure and goshimmer dashboard
iotaledger/iota-core pull request #36
Opened 2023-04-18 07:13 UTC by daria305

[Fixes]https://github.com/iotaledger/iota-core/issues/27) 
[Fixes](https://github.com/iotaledger/iota-core/issues/28)
 - Initial version of dashboard and explorer, with only basic metrics enabled, like BPS, tips count, visualizer and block explorer

2023-04-19 07:13 UTC, jonastheis requested changes

2023-04-19 07:13 UTC, jonastheis commented on components/coreapi/blocks.go
> +func blockBytesByID(c echo.Context) ([]byte, error) {
there's a lot of duplicate code here. I think all 3 methods can be combined to always parse the blockIDParam and get it from the engine and afterwards extract the necessary information / format

2023-04-19 07:13 UTC, jonastheis commented on components/dashboard/component.go
> +			return true
I think we should have a parameter to disable it, just like in the coreapi plugin

2023-04-19 14:25 UTC, daria305 commented on components/dashboard/frontend/src/app/components/AliasOutputComponent.tsx.tsx
nah we just copy pasted this one from goshimmer, but I think it might stay we will have accounts outputs then we will just update it soon

2023-04-20 05:43 UTC, jonastheis approved these changes

2023-04-20 06:53 UTC, merged