Fix Engine shutdown races
iotaledger/iota-core pull request #439
Opened 2023-10-17 13:12 UTC by karimodm

Fixes #438 and #435

2023-10-17 14:10 UTC, hmoog approved these changes
LGTM

2023-10-19 06:27 UTC, jonastheis requested changes

2023-10-19 06:27 UTC, jonastheis commented on pkg/protocol/engine/blockdag/inmemoryblockdag/blockdag.go
> -			panic("cannot setup block without existing parent")
Would be better to log (error handler for now) an error here no?

2023-10-19 06:27 UTC, jonastheis commented on pkg/protocol/engine/engine.go
> +			time.Sleep(5 * time.Second)
Remove debug

2023-10-19 09:45 UTC, alexsporn approved these changes
Fix the comments from Jonas, rest LGTM

2023-10-19 11:18 UTC, jonastheis approved these changes

2023-10-19 11:18 UTC, merged