Forward blocks with semantically invalid txs
iotaledger/iota-core pull request #637
Opened 2023-12-20 11:42 UTC by PhilippGackstatter

Forward blocks with semantically invalid txs.

2024-01-08 20:56 UTC, cyberphysic4l commented on pkg/protocol/engine/booker/inmemorybooker/booker.go
> +		b.setupBlock(block)
I think this is correct, and we do not need to set spenderIDs because the transactions is not booked.

2024-01-08 20:59 UTC, cyberphysic4l commented on pkg/tests/reward_test.go
>  	// node2 should be added in the assertion when issue iotaledger/iota-core#580 is fixed.
Great that this works as expected. We can remove the TODO here of course.

2024-01-10 09:46 UTC, jonastheis commented on pkg/tests/booker_test.go
> +	ts.AssertTransactionFailure(lo.PanicOnErr(tx1.ID()), iotago.ErrIssuerFeatureNotUnlocked, node1, node2)
Would be good to assert here that the block becomes accepted/confirmed. Optional: if you continue issuing until the slot is committed you could check that the tx is not included in the commitment but the block is.

2024-01-10 12:19 UTC, piotrm50 approved these changes

2024-01-12 07:40 UTC, jonastheis approved these changes
Looks good! I just marked some minor simplifications for the test

2024-01-12 07:40 UTC, jonastheis commented on pkg/tests/booker_test.go
> +	vblock1 := ts.IssueValidationBlockWithHeaderOptions("vblock1", ts.DefaultWallet().Node, mock.WithWeakParents(block1.ID()), mock.WithStrongParents(tip))
```suggestion
	vblock1 := ts.IssueValidationBlockWithHeaderOptions("vblock1", ts.DefaultWallet().Node, mock.WithWeakParents(block1.ID()), mock.WithStrongParents(ts.Block("Genesis").ID()))
```

2024-01-12 07:40 UTC, jonastheis commented on pkg/tests/booker_test.go
>  	ts.AssertTransactionFailure(lo.PanicOnErr(tx1.ID()), iotago.ErrIssuerFeatureNotUnlocked, node1, node2)
```suggestion
	ts.AssertTransactionsExist([]*iotago.Transaction{tx1.Transaction}, true, ts.Nodes()...)
	ts.AssertTransactionFailure(lo.PanicOnErr(tx1.ID()), iotago.ErrIssuerFeatureNotUnlocked, ts.Nodes()...)
```

2024-01-12 08:02 UTC, piotrm50 requested changes

2024-01-12 08:02 UTC, piotrm50 commented on pkg/protocol/engine/mempool/v1/transaction_metadata.go
> +			if t.invalid.Get() != nil || !t.IsConflictAccepted() || !t.AllInputsAccepted() {
I think `t.invalid.Get() != nil` should also be checked in other cases: `input.OnAccepted(func() {` (line 256) and `if t.AllInputsAccepted() && t.EarliestIncludedAttachment().Slot() != 0 {` (line 243)

2024-01-12 11:32 UTC, piotrm50 approved these changes

2024-01-12 11:49 UTC, merged