Add cache for core API `validators/`
iotaledger/iota-core pull request #825
Opened 2024-03-11 05:48 UTC by jkrvivian

Close #752 

* Request validators by epoch instead of slot
* Remove granularity in validators API
* Add option to set the maximum size of cache, default to 2MB
* In validators API:
   * Always request the node for validators if `requested_Epoch == current_Epoch` 
   * Keep validatorsResponse in cache `requested_Epoch < current_Epoch`
* Add unit test and docker test for validators API

2024-03-11 07:32 UTC, alexsporn commented on pkg/requesthandler/accounts.go
>  	page := registeredValidators[cursorIndex:lo.Min(cursorIndex+pageSize, uint32(len(registeredValidators)))]
we need some checks here since cursorIndex can be passed from the outside

2024-03-12 21:14 UTC, daria305 requested changes
Really nice test, if you could also remove 'Test_Validators' with its todos from coreapi_test.go after merging develop

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/accounts.go
>  		resp.Cursor = ""
We could have single `if` here as Cursor is already empty
```
// not the last page
if int(cursorIndex+pageSize) <= len(registeredValidators) {
resp.Cursor = fmt.Sprintf("%d,%d", epochIndex, cursorIndex+pageSize)
}
```

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/accounts.go
> +	if cursorIndex >= pageEndIndex {
In simpler terms this could be 
`int(cursorIndex) >= len(registeredValidators)`
and we can check is `pageSize==0` at the beginning

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/requesthandler.go
> +func WithCacheMaxSizeOptions(size int) options.Option[RequestHandler] {
We should use it, or remove it

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/requesthandler.go
> +		optsCacheMaxSize: 2 << 20, // 2MB
What about adding it to parameters next to `restapi.ParamsRestAPI.MaxPageSize`?

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/accounts.go
> +func (r *RequestHandler) registeredValidatorsFromCache(epochIndex iotago.EpochIndex, key []byte) ([]*api.ValidatorResponse, error) {
It could be nicer if the cache mechanics would be more separated, like this would be the method in `cache/cache.go`
Or at least wrap the second of creating the cache in some `Store` func
```go
if registeredValidatorsBytes == nil {
// get the ordered registered validators list from engine.
registeredValidators, err := r.protocol.Engines.Main.Get().SybilProtection.OrderedRegisteredCandidateValidatorsList(epochIndex)
if err != nil {...}
err := r.registeredValidatorsCache.Store(key, registeredValidators)
```

2024-03-12 21:14 UTC, daria305 commented on pkg/requesthandler/accounts.go
> +	validatorResp := make([]*api.ValidatorResponse, 0)
Following the above suggestion we could do decoding in `Cache` logic and already get `[]*api.ValidatorResponse`

2024-03-13 08:54 UTC, daria305 approved these changes

2024-03-14 09:46 UTC, merged