Unify Wallets: Part 1
iotaledger/iota-core pull request #837
Opened 2024-03-14 10:29 UTC by cyberphysic4l

This is the first part of the process to unify the wallets of the testsuite and the docker test framework. This part deals with the testsuite side (the mock wallet) by removing the direct connection to the node within the testsuite. Instead, the mock wallet uses a client interface which matches the nodeclient used in the docker tests, but this mock client simply connects directly to the node. 

The ultimate goal is to allow a common wallet to be used by the testsuite and the docker wallet so transaction and block creation tools do not need to be replicated in both frameworks.

2024-03-15 11:14 UTC, muXxer requested changes

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/wallet_blocks.go
> +	block, err := w.BlockIssuer.IssueBasicBlock(ctx, blockName, opts...)
Why not simply return here?

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/wallet.go
> +func (w *Wallet) SetCurrentSlot(slot iotago.SlotIndex) {
Wouldn't it make sense to set that in the mocked client instead?
This way you also don't have to do the type switch in the "CurrentSlot()".

2024-03-15 11:14 UTC, muXxer commented on pkg/requesthandler/transaction.go
> +func (r *RequestHandler) BlockMetadataFromTransactionID(txID iotago.TransactionID) (*api.BlockMetadataResponse, error) {
Move the function above the `TransactionMetadataFromTransactionID`, so we have everything block related first.

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/blocks.go
> +	//mustNodes(nodes)
```suggestion
```

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/block_params.go
> -func WithSkipReferenceValidation(skipReferenceValidation bool) func(builder *BlockHeaderParams) {
So how do we set the `ReferenceValidation` parameter now?

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/storage_settings.go
> +	//mustNodes(nodes)
```suggestion
```

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/blockissuer.go
> +	_, pub := i.keyManager.KeyPair()
It looks weird that in the constructor you can pass an `addressIndex`, so the account address changes, but here it does not. Is this correct?

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/blockissuer.go
> +			fmt.Printf("revive chain commitment: slot %d, parentID %s\n", commitment.Slot, parentID)
Do we need this print?

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/blockissuer.go
> +	_, pub := i.keyManager.KeyPair()
Is always only the first index used?

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/blockissuer.go
> +	i.mutex.Lock()
```suggestion
	i.mutex.Lock()
	defer i.mutex.Unlock()
```

2024-03-15 11:14 UTC, muXxer commented on pkg/testsuite/mock/blockissuer.go
> +	if i.blockIssuanceResponseUsed {
I don't get why we change it in this function, maybe you can add some comments how the logic of this `blockIssuanceResponseUsed` is supposed to work?

2024-03-18 08:51 UTC, jkrvivian requested changes

2024-03-18 08:51 UTC, jkrvivian commented on pkg/requesthandler/accounts.go
> +			return nil, ierrors.Wrapf(echo.ErrBadRequest, "slot index (%d) before genesis slot (%d)", slot, genesisSlot)
```suggestion
			return nil, ierrors.WithMessagef(echo.ErrBadRequest, "slot index (%d) before genesis slot (%d)", slot, genesisSlot)
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/requesthandler/blocks.go
> +					return nil, ierrors.Wrapf(echo.ErrInternalServerError, "failed to get root blocks for slot %d: %s", blockID.Slot(), err)
```suggestion
					return nil, ierrors.WithMessagef(echo.ErrInternalServerError, "failed to get root blocks for slot %d: %s", blockID.Slot(), err)
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/requesthandler/blocks.go
> +					return nil, ierrors.Wrapf(echo.ErrInternalServerError, "failed to check if block %s is root block: %s", blockID.ToHex(), err)
```suggestion
					return nil, ierrors.WithMessagef(echo.ErrInternalServerError, "failed to check if block %s is root block: %s", blockID.ToHex(), err)
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/requesthandler/transaction.go
> +		return nil, ierrors.Wrapf(echo.ErrNotFound, "failed to get block ID from transaction ID: %v", err)
```suggestion
		return nil, ierrors.WithMessagef(echo.ErrNotFound, "failed to get block ID from transaction ID: %v", err)
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/testsuite/mock/blockissuer.go
> +	// LatestBlockIssuanceResp is the cached response from the latest query to the block issuance endpoint.
```suggestion
	// latestBlockIssuanceResp is the cached response from the latest query to the block issuance endpoint.
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/testsuite/mock/blockissuer.go
> +	i.mutex.Lock()
```suggestion
	i.mutex.Lock()
	defer i.mutex.Unlock()
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/testsuite/mock/blockissuer.go
> +	i.mutex.Lock()
```suggestion
	i.mutex.Lock()
	defer i.mutex.Unlock()
```

2024-03-18 08:51 UTC, jkrvivian commented on pkg/testsuite/mock/node.go
> +func ClientsForNodes(nodes []*Node) []Client {
There's a `ClientsForNodes` method in Testsuite, do we still need this function?

2024-03-18 08:51 UTC, jkrvivian commented on pkg/testsuite/testsuite.go
> +		t.nodes.ForEach(func(_ string, node *mock.Node) bool {
Is there a `t.Nodes()` method that returns all nodes?
If yes, we could replace the forEach here and remove the RLock above.

2024-03-19 13:02 UTC, muXxer approved these changes

2024-03-19 13:02 UTC, merged