Add BlockRetainer cache
iotaledger/iota-core pull request #840
Opened 2024-03-15 06:19 UTC by daria305

Fixes #815 
- blocks are stored under it's `blockID` slot index
 - up until slot commitment blocks metadata are kept in a shrinking map
 - on commitment of slot, all in-mem data is deleted up until slot and stored in the slot-based storage
 - unlike in tx retainer, block metadata can still change after the commitment - on confirmation
 - Reset func clears the shrinking maps and reset all the confirmed statuses to accepted for `slots=(lattestFinalisedSlot, commitedSlot]` as we are not sure if after resetting future slots confirmation will still hold

2024-03-16 11:07 UTC, muXxer requested changes

2024-03-16 11:07 UTC, muXxer commented on pkg/requesthandler/blocks.go
> +			return nil, ierrors.Wrapf(echo.ErrNotFound, "block not found: %s", blockID.ToHex())
Please use `WithMessagef` to maintain the correct error order in this case. We go from less detailed to more detailed errors.

2024-03-16 11:07 UTC, muXxer commented on pkg/requesthandler/blocks.go
> +		if ierrors.Is(err, blockretainer.ErrEntryNotFound) {
Why is there a specific NotFound error in the blockretainer? Either it's in the cache, or we have to look in the database and then we can also use the kvstore error here.

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +var ErrEntryNotFound = ierrors.New("block metadatanot found")
```suggestion
var ErrEntryNotFound = ierrors.New("block metadata not found")
```

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +			return api.BlockStateUnknown, ErrEntryNotFound
you can also return the `kvstore.ErrKeyNotFound` here instead. I think this is a valid simplification.

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +
```suggestion
```

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +		store.ResetConfirmations()
I'm not sure we need this magic at all. Let's discuss this in a short huddle with @piotrm50

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +		return nil, err
```suggestion
		return nil, ierrors.Wrapf(err, "could not get retainer store for slot %d", blockID.Slot())
```

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer.go
> +	})
Why do we need this `slots` variable? Can't we combine the following logic directly with this `ForEach` loop?

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer_cache.go
> +	blocks, exists := c.uncommittedBlockMetadataChanges.Get(blockID.Slot())
Use `GetOrCreate`

2024-03-16 11:07 UTC, muXxer commented on pkg/retainer/blockretainer/block_retainer_cache.go
> +	c.uncommittedBlockMetadataChanges.Set(blockID.Slot(), blocks)
I think you might not need the `Set` if you use `GetOrCreate`, because you are pointing to the same map anyway.
Without it, this might be racy.

2024-03-16 11:07 UTC, muXxer commented on pkg/storage/prunable/slotstore/block_metadata.go
> +		// but we are not sure if the confirmation would still hold if the proceeding slots were cleared out
```suggestion
		// we can safely assume the status is accepted for the committed blocks
		// but we are not sure if the confirmation would still hold if the proceeding slots were cleared out
```

2024-03-16 11:07 UTC, muXxer commented on pkg/storage/prunable/slotstore/block_metadata.go
> +	err := r.blockMetadataStore.Iterate(kvstore.EmptyPrefix, func(key iotago.BlockID, value *BlockMetadata) bool {
```suggestion
	if err := r.blockMetadataStore.Iterate(kvstore.EmptyPrefix, func(key iotago.BlockID, value *BlockMetadata) bool {
```

2024-03-16 11:07 UTC, muXxer commented on pkg/storage/prunable/slotstore/block_metadata.go
> +	})
```suggestion
	}); err != nil {
```

2024-03-18 07:48 UTC, jkrvivian requested changes

2024-03-18 07:48 UTC, jkrvivian commented on pkg/retainer/blockretainer/block_retainer_cache.go
> +func newCache(opts ...options.Option[cache]) *cache {
We don't need options for cache.

2024-03-18 07:48 UTC, jkrvivian commented on pkg/retainer/blockretainer/block_retainer_cache.go
> +	uncommittedBlockMetadataChanges *shrinkingmap.ShrinkingMap[iotago.SlotIndex, map[iotago.BlockID]api.BlockState]
`uncommittedBlockMetadata` would be clear enough :stuck_out_tongue:

2024-03-18 07:48 UTC, jkrvivian commented on pkg/retainer/blockretainer/block_retainer.go
> +	state, found := r.cache.blockMetadataByID(blockID)
```suggestion
	state, found := r.cache.blockMetadataByID(blockID)
```

2024-03-18 20:56 UTC, muXxer approved these changes

2024-03-18 20:56 UTC, merged